### ISSUE TITLE
Timezone CEST + picon URL fix

### ISSUE THREAD

**Issue by wylda** [frantisheq/rbxmltv-data#1]
Dobrý den,
zkusil jsem Váš cz-sk.xml a narazil na to, že programy jsou o 1hod posunuté díky CEST.

Vzhledem k letnímu 2h posunu - bylo by možné změnit +0100 na +0200? Pak je to
na RPi + Tvheadend OK.

Následující URL picon vrací 404, ale oprava URL je jednoduchá:
barrandov-family.png  =>  barrandov_family.png
barrandov-krimi.png  =>  barrandov_krimi.png
joj-family.png  =>  joj_family.png
nova-2.png  =>  nova_2.png
nova-action.png  =>  nova_action.png
nova-cinema.png  =>  nova_cinema.png
nova-gold.png  =>  nova_gold.png
prima-comedy-central.png  =>  prima_comedy_central.png
prima-cool.png  =>  prima_cool.png
prima-krimi.png  =>  prima_krimi.png
prima-max.png  =>  prima_max.png
prima-plus.png  =>  prima_plus.png
prima-zoom.png  =>  prima_zoom.png

Náhodou Prima+1 by nebyla? ;c))

A poslední věc při kontrole jsem si všiml, že XML obsahuje v 20200411201500 na Primě "Temný kraj", ale ve skutečnosti bylo v oficiálních programech "Vlna naděje".

Díky moc za XMLko.

**Comment by frantisheq** [comment]
opravene. Prima+1 az ked sa objavi na tvp.cz.
